### ISSUE TITLE
Crear servicio no funciona

### ISSUE THREAD

**Issue by lgtoledo** [bITAMINAS/histocar_project#10]
Chasky, el crear servicio no funciona. Al darle guardar me marca en rojo el campo de Estado.
Me imagino que le agregaste algún tipo de validación que no está funcionando.
Yo le había agregado que fuera de tipo combo box(Select) para que sólo dejara seleccionar un elemento.

**Comment by todobanners** [comment]
El problema es el combo select, dice el error que espera una lista de valores, la cual no le llega por alguna verificación de django sobre los formularios, hay que ver como saltarla. Mientras tanto funciona como un combo multiple y no hay problema. Creo que la otra opcion es introducir manualmente los campos que se quieren. Incluso intente con borrar la propiedad "multiple" del campo mediante java script y daba el mismo error. Saque la propiedad selelct y funciona bien.

**Comment by todobanners** [comment]
Solucionado con el commit en rama eduardo
8999e1f51ca782f2af3184a4e942840306717695

Si lo aceptan hagan merge a desarrollo.
se cambia el tipo de relación en la base de datos. Por lo tanto hay que migrar. mi DB ya esta actualizada así que no hay problemas, prueben y me dicen!

**Comment by todobanners** [comment]
Solución encontrada en commit ca3b1ba45cf159a05b2d71f894b006712295c8f3
basado en la respuesta a la pregunta en
https://stackoverflow.com/questions/14969969/django-representing-user-groups-manytomanyfield-as-a-select-in-form
Puede haber algún problema con los import, pero a grandes rasgos anda bien, esta funcionando en www.todobanners.pythonanywhere.com
